### ISSUE TITLE
`required_pkgs` and "engine"

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/textrecipes#111]
Related to #110 

The recipe step `step_tokenize()` has the idea of an "engine", i.e. it can either use tokenizers or spacyr for tokenization. Neither is currently listed in `required_pkgs` for this step, but certainly you wouldn't want _both_ to be listed. This means that as of now, these packages will not get correctly loaded into workers for many situations.

**Comment by EmilHvitfeldt** [comment]
This appears to have been fixed

https://github.com/tidymodels/textrecipes/blob/2c4591ee8b34051f7504646da987d2d855ae436d/R/tokenize.R#L467-L479
