### ISSUE TITLE
stopwords

### ISSUE THREAD

**Issue by tleitch** [tidymodels/textrecipes#115]
< -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

## Feature

I used textrecipes for a small problem and was experimenting with n-grams with n>1 and was surprised that stop words were not removed for higher n. When I have implemented stop word elimination on my own, I remove them before i do any tokenization, so I expected them to be removed in the higher n cases. This left a lot of bigrams and trigrams with stop words leading them which was low info content result. It would be good to be able to do the stop word before tokenization in order to achieve higher info content dataset. 

Code (I settled for n=1):
rec <- recipe(Product ~ ., data = training_data) %>%
  step_tokenize(complaint_text) %>%
  step_stopwords(complaint_text,custom_stopword_source = customStop)%>%
  step_tokenfilter(complaint_text, max_tokens = 500) %>%
  step_tfidf(complaint_text) %>%
  themis::step_upsample(Product) %>%
  prep()

**Comment by juliasilge** [comment]
The best way to do this right now with textrecipes is [how we demonstrate in this section of our book](https://smltar.com/mlregression.html#mlregressionfull).

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(textrecipes)

data("small_fine_foods", package = "modeldata")

food_rec <- recipe(score ~ review, data = training_data) %>%
  step_tokenize(
    review,
    token = "ngrams",
    options = list(
      n = 2, n_min = 1,
      stopwords = stopwords::stopwords(source = "snowball")
    )
  ) %>%
  step_tokenfilter(review, max_tokens = 500) %>%
  step_tfidf(review)

food_rec
#> Data Recipe
#> 
#> Inputs:
#> 
#>       role #variables
#>    outcome          1
#>  predictor          1
#> 
#> Operations:
#> 
#> Tokenization for review
#> Text filtering for review
#> Term frequency-inverse document frequency with review
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by EmilHvitfeldt** [comment]
Julia is correct with the use of `token = "ngrams"` in `step_tokenize()`. If you want even more flexibility of what happens between tokenization and ngramming you can tokenize to unigrams with `step_tokenize()`, do your modifications and then follow up with `step_ngram()` to turn the remaining unigrams into ngrams. the main difference here is the name of the columns.

``` r
library(recipes)
library(textrecipes)

example <- tibble(text = c("there once was a ship that put to sea"))

recipe(~ text, data = example) %>%
  step_tokenize(
    text,
    token = "ngrams",
    options = list(
      n = 2, n_min = 2,
      stopwords = c("a")
    )
  ) %>%
  step_tf(text) %>%
  prep() %>%
  bake(new_data = example)
#> # A tibble: 1 x 7
#>   `tf_text_once was` `tf_text_put to` `tf_text_ship that` `tf_text_that put`
#>                <dbl>            <dbl>               <dbl>              <dbl>
#> 1                  1                1                   1                  1
#> # … with 3 more variables: tf_text_there once <dbl>, tf_text_to sea <dbl>,
#> #   tf_text_was ship <dbl>

recipe(~ text, data = example) %>%
  step_tokenize(text) %>%
  step_stopwords(text, custom_stopword_source = c("a")) %>%
  step_ngram(text, num_tokens = 2, min_num_tokens = 2) %>%
  step_tf(text) %>%
  prep() %>%
  bake(new_data = example)
#> # A tibble: 1 x 7
#>   tf_text_once_was tf_text_put_to tf_text_ship_that tf_text_that_put
#>              <dbl>          <dbl>             <dbl>            <dbl>
#> 1                1              1                 1                1
#> # … with 3 more variables: tf_text_there_once <dbl>, tf_text_to_sea <dbl>,
#> #   tf_text_was_ship <dbl>
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
