### ISSUE TITLE
problem when step_tf() is used for term frequency combined with step_tokenfilter()

### ISSUE THREAD

**Issue by jjcurtin** [tidymodels/textrecipes#118]
`step_tf()` with `weight_scheme = "term frequency"` does not work as I would expect when combined with `step_tokenfilter()`.

It appears that the raw counts for the tokens are not divided by the length of the original document.

Instead, raw counts are divided by the sum of raw counts of the tokens that remain after filtering.

Dividing by the sum of the tokens after filtering also causes problems when a document
exists that has raw counts of 0 for all of the tokens retained after filtering.  For such a document, the
results are NaN rather than zero for all the tokens.

Both of these issues are demonstrated below.  The original documents all contain five tokens.

I filtered so that only the top four tokens are retained.  Document 3 does not contain
any of these tokens

I would have expected term frequencies of .4 or .2 for the tokens that have raw counts of 1 or 2 per document because the 
denominator of those values should have been 5.  Instead, the term frequencies are .25 or .50 such that it appears the denominator was 4.

I would have expected term frequencies of 0 for all the retained (after filtering) tokens in the third document b/c they 
had raw counts of 0.  Instead the denominator appears to be 0, yielding NaN

---

Load packages
``` r
library(tidyverse)
library(textrecipes)
#> Loading required package: recipes
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stringr':
#> 
#>     fixed
#> The following object is masked from 'package:stats':
#> 
#>     step

d <- tibble(docs = c("the document one one novel1",
                     "the document two two novel2",
                     "novel3 novel4 novel5 novel6 novel7"),
            y = c("y", "y", "n")) %>% 
  print()
#> # A tibble: 3 x 2
#>   docs                               y    
#>   <chr>                              <chr>
#> 1 the document one one novel1        y    
#> 2 the document two two novel2        y    
#> 3 novel3 novel4 novel5 novel6 novel7 n

rec <- recipe (y ~ docs, data = d) %>% 
  step_tokenize(docs) %>%
  step_tokenfilter(docs, max_tokens = 4) %>% 
  step_tf(docs, weight_scheme = "term frequency")

rec %>% 
  prep() %>% 
  bake(d)
#> # A tibble: 3 x 5
#>   y     tf_docs_document tf_docs_one tf_docs_the tf_docs_two
#>   <fct>            <dbl>       <dbl>       <dbl>       <dbl>
#> 1 y                 0.25         0.5        0.25         0  
#> 2 y                 0.25         0          0.25         0.5
#> 3 n               NaN          NaN        NaN          NaN
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by EmilHvitfeldt** [comment]
After mulling over this issue I have decided to make a change to return 0 if there aren't any tokens present when doing `step_tf()` with `weight_scheme = "term frequency"`. This will remove some headache for people.

I won't make a change to have the term frequencies be calculated based on the original document, as there are multiple reasons why the tokens can change over time.

An example where this would be a hard change is when we look at ways the token count can increase. See n-gram example below. How would the base document token rates work? What if you filter before n-gramming?

``` r
library(tidyverse)
library(textrecipes)

d <- tibble(docs = c("the document one one",
                     "the document two two",
                     "novel3 novel4 novel5 novel6 novel7"),
            y = c("y", "y", "n")) %>% 
  print()
#> # A tibble: 3 × 2
#>   docs                               y    
#>   <chr>                              <chr>
#> 1 the document one one               y    
#> 2 the document two two               y    
#> 3 novel3 novel4 novel5 novel6 novel7 n

rec <- recipe (y ~ docs, data = d) %>% 
  step_tokenize(docs) %>%
  step_ngram(docs, min_num_tokens = 2, num_tokens = 2) %>%
  step_tokenfilter(docs, max_tokens = 3) %>% 
  step_tf(docs, weight_scheme = "term frequency")

rec %>% 
  prep() %>% 
  bake(d)
#> # A tibble: 3 × 4
#>   y     tf_docs_document_one tf_docs_document_two tf_docs_the_document
#>   <fct>                <dbl>                <dbl>                <dbl>
#> 1 y                      0.5                  0                    0.5
#> 2 y                      0                    0.5                  0.5
#> 3 n                    NaN                  NaN                  NaN
```

<sup>Created on 2022-01-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Other than preferences, I don't see a performance reason why this change should be made (I would be happy to be proven wrong).
