### ISSUE TITLE
Select variables in recipe

### ISSUE THREAD

**Issue by guivivi** [tidymodels/textrecipes#120]
Dear Emil Hvitfeldt. First of all, many thanks for your amazing work. Following the help file of step_tokenize (specifically, the explanation of argument ...), I am trying to choose a subset of variables. For example, I would just want to work with columns "tfidf_text_love" and "tfidf_text_hate".  I am trying this:
 
`data_rec <- recipe(target ~ text, data = data_train) %>%`
`step_tokenize(text) %>%`
`step_tokenfilter(text, max_tokens = 2, contains("hate|love")) %>%`
`step_tfidf(text)`

`data_prep <- prep(data_rec)`
`data_bake <- bake(data_prep, new_data = data_test)`

However, `colnames(data_bake)` are not "tfidf_text_love" and "tfidf_text_hate"

Could you please tell me how we can do this?

Guillermo

**Comment by topepo** [comment]
`recipes` has [`step_rm()`](https://recipes.tidymodels.org/reference/step_rm.html) and [`step_select()`](https://recipes.tidymodels.org/reference/step_select.html) to remove and retain columns (respectively).

**Comment by guivivi** [comment]
Many thanks for the help, Max. Congratulations to all for this outstanding work.
