### ISSUE TITLE
C stack usage  15923888 is too close to the limit

### ISSUE THREAD

**Issue by jacekkotowski** [tidymodels/textrecipes#121]
I get an error with new version 0.40 (works in previous released version)
Error: C stack usage  15923888 is too close to the limit

My code is loading simple text files in English (bank reports). The code works in the previous version (step_stem() not used then). In the new version, it throws an error regardless if I try using step_stem() or not (commented out) it fails on step_tokenize() 

My code: 

```r
pacman::p_load(tidymodels, textrecipes)

tbl <-
  list.files(
    path = "dane/minutes_nbp_en_text/",
    pattern = "*.txt",
    full.names = TRUE) %>%
  map_chr(~ read_file(.)) %>%
  data_frame(id = 1:length(.), text = .)

okc_rec <-
  recipe(~  text, data = tbl) %>%
  step_tokenize(text) %>% # Tokenizes to words by default, tested at this point it will throw an error. 
  step_stem(text) %>% # commented out will not change anything
  step_stopwords(text) %>% # Uses the english snowball list by default
  step_tokenfilter(text, max_tokens = 100) %>%
  step_tfidf(text)

okc_obj <- okc_rec %>%
  prep() %>%
  juice()
```

Hardware: Laptop 16GB RAM i7 core with Windows 10

**Comment by EmilHvitfeldt** [comment]
Hello @jacekkotowski! I'm sorry to hear you are running into issues.

I'm not able to reproduce your error. Can you copy the following code to the clipboard and run: `reprex::reprex(si = TRUE)` and then post the results back in here? thank you

``` r
library(textrecipes)

data("okc_text", package = "modeldata")
okc_rec <-
  recipe(~ essay0, data = okc_text) %>%
  step_tokenize(essay0)

okc_obj <- okc_rec %>%
  prep() %>%
  juice()

okc_obj

```

**Comment by jacekkotowski** [comment]
It seems to work well, here is the result of reprex:

library(textrecipes)
#> Loading required package: recipes
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

data("okc_text", package = "modeldata")
okc_rec <-
  recipe(~ essay0, data = okc_text) %>%
  step_tokenize(essay0)

okc_obj <- okc_rec %>%
  prep() %>%
  juice()

okc_obj
#> # A tibble: 750 x 1
#>          essay0
#>       <tknlist>
#>  1 [184 tokens]
#>  2  [24 tokens]
#>  3 [375 tokens]
#>  4  [77 tokens]
#>  5  [77 tokens]
#>  6 [275 tokens]
#>  7 [327 tokens]
#>  8 [155 tokens]
#>  9   [4 tokens]
#> 10 [592 tokens]
#> # ... with 740 more rows
Created on 2021-05-26 by the reprex package (v2.0.0)

 Session info
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.0 (2021-05-18)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Polish_Poland.1250          
#>  ctype    Polish_Poland.1250          
#>  tz       Europe/Warsaw               
#>  date     2021-05-26                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib
#>  assertthat    0.2.1      2019-03-21 [1]
#>  backports     1.2.1      2020-12-09 [1]
#>  class         7.3-19     2021-05-03 [1]
#>  cli           2.5.0      2021-04-26 [1]
#>  crayon        1.4.1      2021-02-08 [1]
#>  DBI           1.1.1      2021-01-15 [1]
#>  digest        0.6.27     2020-10-24 [1]
#>  dplyr       * 1.0.6      2021-05-05 [1]
#>  ellipsis      0.3.2      2021-04-29 [1]
#>  evaluate      0.14       2019-05-28 [1]
#>  fansi         0.5.0      2021-05-25 [1]
#>  fs            1.5.0      2020-07-31 [1]
#>  generics      0.1.0      2020-10-31 [1]
#>  glue          1.4.2      2020-08-27 [1]
#>  gower         0.2.2      2020-06-23 [1]
#>  highr         0.9        2021-04-16 [1]
#>  htmltools     0.5.1.1    2021-01-22 [1]
#>  ipred         0.9-11     2021-03-12 [1]
#>  knitr         1.33       2021-04-24 [1]
#>  lattice       0.20-44    2021-05-02 [1]
#>  lava          1.6.9      2021-03-11 [1]
#>  lifecycle     1.0.0      2021-02-15 [1]
#>  lubridate     1.7.10     2021-02-26 [1]
#>  magrittr      2.0.1      2020-11-17 [1]
#>  MASS          7.3-54     2021-05-03 [1]
#>  Matrix        1.3-3      2021-05-04 [1]
#>  nnet          7.3-16     2021-05-03 [1]
#>  pillar        1.6.1      2021-05-16 [1]
#>  pkgconfig     2.0.3      2019-09-22 [1]
#>  prodlim       2019.11.13 2019-11-17 [1]
#>  ps            1.6.0      2021-02-28 [1]
#>  purrr         0.3.4      2020-04-17 [1]
#>  R6            2.5.0      2020-10-28 [1]
#>  Rcpp          1.0.6      2021-01-15 [1]
#>  recipes     * 0.1.16     2021-04-16 [1]
#>  reprex        2.0.0      2021-04-02 [1]
#>  rlang         0.4.11     2021-04-30 [1]
#>  rmarkdown     2.8        2021-05-07 [1]
#>  rpart         4.1-15     2019-04-12 [1]
#>  rstudioapi    0.13       2020-11-12 [1]
#>  sessioninfo   1.1.1      2018-11-05 [1]
#>  SnowballC     0.7.0      2020-04-01 [1]
#>  stringi       1.6.2      2021-05-17 [1]
#>  stringr       1.4.0      2019-02-10 [1]
#>  styler        1.4.1      2021-03-30 [1]
#>  survival      3.2-11     2021-04-26 [1]
#>  textrecipes * 0.4.0.9000 2021-05-25 [1]
#>  tibble        3.1.2      2021-05-16 [1]
#>  tidyr         1.1.3      2021-03-03 [1]
#>  tidyselect    1.1.1      2021-04-30 [1]
#>  timeDate      3043.102   2018-02-21 [1]
#>  tokenizers    0.2.1      2018-03-29 [1]
#>  utf8          1.2.1      2021-03-12 [1]
#>  vctrs         0.3.8      2021-04-29 [1]
#>  withr         2.4.2      2021-04-18 [1]
#>  xfun          0.23       2021-05-15 [1]
#>  yaml          2.2.1      2020-02-01 [1]
#>  source                                 
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  Github (tidymodels/textrecipes@74414f5)
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#>  CRAN (R 4.1.0)                         
#> 
#> [1] C:/R/R-4.1.0/library

**Comment by EmilHvitfeldt** [comment]
No problem! Please open other issues if you think you found another problem :)
