### ISSUE TITLE
Error in loadNamespace(x) : there is no package called ‘stopwords’

### ISSUE THREAD

**Issue by jcragy** [tidymodels/textrecipes#131]
Hi, I was doing the tutorial Julia Silge showed us on YouTube: https://www.youtube.com/watch?v=VwZKK6kldqo

She's building a tidymodels recipe with textrecipes . I did everything the same and when I try to 'prep' and 'bake' the recipe, I get that error **Error in loadNamespace(x) : there is no package called ‘stopwords’**

recipe <- recipe(price ~ latitude + longitude + neighbourhood + room_type + minimum_nights + 
                 number_of_reviews+ availability_365 + name, nyc_train) %>%
        step_novel(neighbourhood) %>%                                          # in case theres new levels in the testing set
        step_other(neighbourhood, threshold = 0.01) %>%              # too many levels, 
        textrecipes::step_tokenize(name) %>%                                   # tokenization for name
        textrecipes::step_stopwords(name) %>%                                # stop word removal for name
        textrecipes::step_tokenfilter(name, max_tokens = 30) %>%   # text filtering for name
        textrecipes::step_tf(name)                                                        # term frequency with name

I don't know if this is a bug because when I installed 'textrecipes' library there is like 2 versions? 
I don't understand. I've never had an issue installing a package before in R

But its definitely throwing an error and wont prep or bake a recipe with 'step_stopwords' feature. I can make the recipe fine, but cannot observe output with prep/bake. But I can observe output with keyword or tidy(recipe) / summary(recipe) 

Thank you

**Comment by juliasilge** [comment]
Hello there @jcragy! Have you tried installing the [stopwords](https://cran.r-project.org/package=stopwords) package, and then running again?

The `required_pkgs` infrastructure seems to be working fine for this step in general so I expect something has gone wonky in your installation:

``` r
library(textrecipes)
#> Loading required package: recipes
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

data(okc_text, package = "modeldata")
rec <- recipe(~ ., data = okc_text) %>%
  step_tokenize(essay0) %>%
  step_stopwords(essay0)

required_pkgs(rec)
#> [1] "recipes"     "textrecipes" "stopwords"
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jcragy** [comment]
That's what it was, I did not have 'stopwords' library installed. 

I was confused because it says it belongs to the 'textrecipes' library, but now when I run the recipe I can prepare and bake it no problems. 

Thank you for the explanation #> [1] "recipes"     "textrecipes" "stopwords", makes sense.

**Comment by juliasilge** [comment]
Good luck!
