### ISSUE TITLE
Support all_tokenized_predictors(), similar to e.g. all_numeric_predictors()

### ISSUE THREAD

**Issue by dgrtwo** [tidymodels/textrecipes#132]
## Feature

The recipes package provides `all_numeric_predictors()` and `all_nominal_predictors()` for applying a recipe to every variable of a particular role and type. It would be great if textrecipes supported something analogous like `all_tokenized_predictors()`.

For example, suppose I wanted to apply the recipe in the README to 9 essays, not just 2:

```
library(recipes)
library(textrecipes)
library(modeldata)

data(okc_text)

# In this case could use `starts_with("essay")`, but general point
# is that I might want to add/remove some variables from the recipe
okc_rec <- recipe(~  ., data = okc_text) %>%
  step_tokenize(essay0, essay1, essay2, essay3, essay4, essay5,
                essay6, essay7, essay8, essay9) %>%
  step_stopwords(has_type("other")) %>%
  step_tokenfilter(has_type("other"), max_tokens = 10) %>%
  step_tfidf(has_type("other"))

okc_rec %>%
  prep() %>%
  juice()
```

Right now, my workaround is `has_type("other")`, as above. This works as long as the only "other" columns are `textrecipes_tokenlist` (especially as tidymodels expands what they use list columns for), and in any case it's harder to understand the intent. (I don't have the understanding of `has_type()` to know if this requires changes to the recipes package as well).

This is especially useful when I'm rapidly changing which columns I decide to include and tokenize (right now, I have to edit every step of the process; not only tokenizing but also stopwords, tokenfilter, stemming and tf/tfidf, and it's easy for them to get out of sync). I find I'm operations like tf in particular are always done on all tokenized predictors.

**Comment by EmilHvitfeldt** [comment]
I like the idea! And just to clarify, you want `all_tokenized_predictors()` too apply to the columns that `step_tokenize()` creates, but not the columns that `step_tf()` creates since they would be captured by `all_numeric_predictocs()` right?

**Comment by dgrtwo** [comment]
Exactly!!

Only columns that are `tokenlst` in the previewed output

**Comment by EmilHvitfeldt** [comment]
Waiting on https://github.com/tidymodels/textrecipes/issues/125
