### ISSUE TITLE
Is tokenlist the right word?

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/textrecipes#143]
I have been thinking of the documentation of the steps in this package. The word "tokenlist" comes around a lot, which is the name of the internal class I'm using. This class will rarely be used by the user, other than by debugging (which poorly supported right now).

Would "token" be a better name for this class and used in documentation? Then we will have sentences such as "step_tokenize() turns character columns into token columns". The full name of the class is `textrecipes_tokenlist` so we wouldn't get any conflicts between other packages with the name change.

Thoughts? @topepo @juliasilge

**Comment by juliasilge** [comment]
Do you mean changing the name of the class or how this is discussed in documentation? 

- I think that changing the documentation to use more everyday language would be more clear, (like "token to character" and similar [in the headings here](https://textrecipes.tidymodels.org/reference/index.html)).
- I am guessing that this wouldn't be a backward compatible change to change the name of the class, though, right? It might not be worth the trouble to change the internal class name.

**Comment by EmilHvitfeldt** [comment]
Originally I was thinking both. But I could be convinced to only change the documentation. This is how things print right now:

``` r
library(textrecipes)
abc <- list(letters, LETTERS)

tokenlist(abc)
#> <textrecipes_tokenlist[2]>
#> [1] [26 tokens] [26 tokens]
#> # Unique Tokens: 52

tibble(text = tokenlist(abc))
#> # A tibble: 2 × 1
#>          text
#>     <tknlist>
#> 1 [26 tokens]
#> 2 [26 tokens]
```

With `textrecipes_tokenlist` and `vec_ptype_abbr.textrecipes_tokenlist()` giving us `tknlist`. I'm not sure, I don't know if changing the name of the class itself is backward compatible. Never tried to do something like this before with a s3 class
