### ISSUE TITLE
Language argument for step_lemma

### ISSUE THREAD

**Issue by DiabbZegpi** [tidymodels/textrecipes#144]
I've noticed that there are multiple language models available in spaCy, such as spanish `es_core_web_sm`. Would be nice to be able to choose the language at the `step_lemma` function.

Does this feature already exists? I didn't found it in textrecipes nor spacyr documentations.

**Comment by juliasilge** [comment]
Currently this happens when you run:

``` r
spacyr::spacy_initialize()
#> Finding a python executable with spaCy installed...
#> spaCy (language model: en_core_web_sm) is installed in more than one python
#> spacyr will use /Users/juliasilge/miniforge3/envs/tf_env/bin/python (because ask = FALSE)
#> successfully initialized (spaCy Version: 3.0.6, language model: en_core_web_sm)
#> (python options: type = "python_executable", value = "/Users/juliasilge/miniforge3/envs/tf_env/bin/python")
```

<sup>Created on 2021-11-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So you can set up which language model to use ahead of time, [when you initialize spaCy](https://spacyr.quanteda.io/reference/spacy_initialize.html) via the `model` argument. I think it might be quite difficult to do this internally in the recipe step.

**Comment by DiabbZegpi** [comment]
Whenever I try to initialize spaCy with `spacy_initialize(model = "es_core_web_sm")` I get the following error:

`Python space is already attached.  If you want to switch to a different Python, please restart R.
ERROR: The requested version of Python
('C:\Users\beatd\AppData\Local\r-miniconda\envs\spacy_condaenv\python.exe')
cannot be used, as another version of Python
('C:/Users/beatd/AppData/Local/Programs/Python/Python38/python.exe')
has already been initialized. Please restart the R
session if you need to attach reticulate to a
different version of Python.
Error in use_python(python, required = required) : 
  failed to initialize requested version of Python`

Does this mean that I have to change the RETICULATE_PYTHON variable?

**Comment by juliasilge** [comment]
I'm guessing that this happens even if you try this in a totally fresh R session, where you have do not believe you have initialized Python, i.e. connected to a Python environment from R? What you need to do is have R connect to the Python environment where you have installed the language model you are interested in.

**Comment by DiabbZegpi** [comment]
I opted for uninstall python, spaCy and reinstall miniconda. This was succesfull in a fresh R session and R project

``` {r}
> library(spacyr)
> spacy_initialize(model = "es_core_news_sm")
Found 'spacy_condaenv'. spacyr will use this environment
successfully initialized (spaCy Version: 3.1.3, language model: es_core_news_sm)
(python options: type = "condaenv", value = "spacy_condaenv")
```

**Comment by DiabbZegpi** [comment]
I'm ashamed. All the time I was writing es_core_web_sm, but python was expecting `es_core_news_sm`. Sorry for the issue.
