### ISSUE TITLE
move to tidymodels org

### ISSUE THREAD

**Issue by topepo** [tidymodels/textrecipes#15]
I will add you as a member of the `tidymodels` org (assuming you still want to keep it there). 

We'll have to do a [transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) and, _I believe_ this can happen once you are a member. 

Let me know if you are still interested.

**Comment by EmilHvitfeldt** [comment]
It sounds great, lets transfer it!

**Comment by topepo** [comment]
Just sent an invite. We ask that you have 2 factor authentication enabled on GH for membership.

**Comment by EmilHvitfeldt** [comment]
- [ ] 2 factor authentication enabled 
- [ ] Moving repository to tidymodels/textrecipes. This may take a few minutes.

**Comment by EmilHvitfeldt** [comment]
It looks like a success. I'll close this issue now
