### ISSUE TITLE
textrecipes is not loading: I get the following error.

### ISSUE THREAD

**Issue by raj-hubber** [tidymodels/textrecipes#177]
I get the following error and it does not load.

> library(textrecipes)
Loading required package: recipes
Error in value[[3L]](cond) : 
  Package ‘recipes’ version 0.1.17 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘recipes’ is imported by ‘caret’ so cannot be unloaded
In addition: Warning messages:
1: package ‘textrecipes’ was built under R version 4.1.3 
2: package ‘recipes’ was built under R version 4.1.3

**Comment by raj-hubber** [comment]
> library(textrecipes)
Loading required package: recipes
Error in value[[3L]](cond) : 
 Package ‘recipes’ version 0.1.17 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘recipes’ is imported by ‘caret’ so cannot be unloaded
In addition: Warning messages:
1: package ‘textrecipes’ was built under R version 4.1.3 
2: package ‘recipes’ was built under R version 4.1.3

**Comment by juliasilge** [comment]
In a situation like this, we recommend restarting R, installing recipes (`install.packages("recipes")`),  and then probably installing textrecipes (`install.packages("textrecipes")`) again. Maybe restart R at that point again for good measure. 😄

**Comment by raj-hubber** [comment]
Thanks, Julia! It got resolved after I updated the dependencies and restarted.
