### ISSUE TITLE
Remove duplicated rows in the post-recipe stage

### ISSUE THREAD

**Issue by PursuitOfDataScience** [tidymodels/textrecipes#193]
Hi,

When using the textrecipes package, I've encountered situations where there are multiple duplicate rows in the post-recipe stage when applying predictive modeling on text. This is because after using `step_tokenfilter()` and `step_tfidf()`, text observations in the raw data might possibly turn out to be the same when the tokenized words become columns. Having duplicated rows is something we should avoid. I am thinking if there is a way like `step_duplicate()` to do so? Thanks!

**Comment by EmilHvitfeldt** [comment]
Can you explain why you think we should avoid duplicate rows? In my opinion this is perfectly valid, as there are times where one or more observations will be identical

**Comment by PursuitOfDataScience** [comment]
Yes, in the case I encountered a little earlier where there were a lot of duplicates after using recipe, it was very expensive to train the model. Having the option of removing the duplicates can allow the model to train faster. Also, I am not sure if this is related to the textrecipes package, but every time when I use `logistic_regression()` to classify some text, it gives an error message `Error in cut.default(seq_along(out), docindex, include.lowest = TRUE, : 'breaks' are not unique` in the `last_fit()` stage.

**Comment by EmilHvitfeldt** [comment]
Interesting, Are you able to provide a reprex? :)

**Comment by PursuitOfDataScience** [comment]
The data is too large and unable to attach anywhere here, but I provide part of the code below:

```
set.seed(2022)
tweet_spl <- tweets  |>
  initial_split(strata = "emoji_tweet")

tweet_train <- training(tweet_spl)
tweet_test <- testing(tweet_spl)

set.seed(123)
tweet_folds <- vfold_cv(tweet_train, strata = "emoji_tweet", v = 3)


tweet_rec <- recipe(emoji_tweet ~ full_text, data = tweet_train) |>
  step_tokenize(full_text, token = "tweets") |>
  step_stopwords(full_text) |>
  step_stem(full_text) |>
  step_tokenfilter(full_text, max_tokens = tune()) |>
  step_tfidf(full_text) |>
  step_downsample(emoji_tweet)

lasso_spec <- logistic_reg(penalty = tune(), mixture = 1) |>
  set_mode("classification") |>
  set_engine("glmnet")


lasso_wf <- workflow() |>
  add_model(lasso_spec) |>
  add_recipe(tweet_rec)


doParallel::registerDoParallel(cores = 3)

lasso_rs <-  lasso_wf |>
  tune_grid(
    tweet_folds,
    grid = crossing(
      max_tokens = c(500, 3000),
      penalty = 10 ^ seq(-7, -1, 1)
    ),
    metrics = metric_set(yardstick::accuracy,
                         yardstick::roc_auc,
                         yardstick::sens,
                         yardstick::spec)
  )


autoplot(lasso_rs_bal) 
```

![image](https://user-images.githubusercontent.com/54338793/188960855-a692647d-05c6-435b-92de-2c34a3d8967c.png)

The above code is fine, but when it comes to `last_fit()`, it gives out the error message I put above. 

```
lasso_last_fit <- lasso_wf |>
  finalize_workflow(select_best(lasso_rs)) |>
  last_fit(split = tweet_spl)

lasso_last_fit 
```

Any ideas of what went wrong?

**Comment by PursuitOfDataScience** [comment]
When I input a value, say 50, to `max_tokens = 50`, and the same problem shows up when bake the recipe:

```
bake(prep(tweet_rec), new_data = NULL) 
```

What it returns is `Error in cut.default(seq_along(out), docindex, include.lowest = TRUE,  : 
  'breaks' are not unique`

Which is rather confusing for the error. I guess the problem stems from `step_tokenfilter()`.

**Comment by PursuitOfDataScience** [comment]
When I remove `token = "tweets"`, the problem goes away. Strange.

**Comment by EmilHvitfeldt** [comment]
This is very likely because of how `tokenizers::tokenize_tweets()` works, and it appears to error when the string is too short

``` r
library(tokenizers)

tokenize_tweets("hello")
#> Error in cut.default(seq_along(out), docindex, include.lowest = TRUE, : 'breaks' are not unique
tokenize_tweets("hello there")
#> [[1]]
#> [1] "hello" "there"
```

I would suggest either using a different tokenization method or to use the developmental version of tokenizers which has this bug fixed https://github.com/ropensci/tokenizers/issues/70

````r
remotes::install_github("ropensci/tokenizers")
````

**Comment by PursuitOfDataScience** [comment]
Yes, I am not sure if this is an error, but using the default tokenization ("word") solved the issue.
