### ISSUE TITLE
Tokenizing tweets is being removed

### ISSUE THREAD

**Issue by lmullen** [tidymodels/textrecipes#208]
Hi. Due to underlying changes to the ICU library and a timetable which is required by CRAN, we have removed `tokenizers::tokenize_tweets()` from the tokenizers package. When this makes it to CRAN, it will cause an error in this package, which uses that function. You can follow [this issue](https://github.com/ropensci/tokenizers/issues/82) for details.

I apologize for the inconvenience. But I believe it will be necessary to remove the use of the `tokenize_tweets()` function from this package.

**Comment by EmilHvitfeldt** [comment]
Thank you @lmullen I will send in a patch right away!

**Comment by lmullen** [comment]
Thanks, @EmilHvitfeldt, and apologies again for the extremely short notice.
