### ISSUE TITLE
regex and embeddings

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/textrecipes#219]
Can embeddings in `step_word_embeddings()` use regex like "benefit*"? or just complete words?

**Comment by EmilHvitfeldt** [comment]
Hello @nipnipj 👋 

It does a full match on the word. Basically like a `left_join()` this means that `bank` and `Bank` are considered different.

There won't be support for regex in `step_word_embeddings()` because it wouldn't be possible to deal with multiple matches in a predictable way.
