### ISSUE TITLE
textfeatures

### ISSUE THREAD

**Issue by topepo** [tidymodels/textrecipes#22]
Can you add a step to generate the basic set of features produced by `textfeatures:: textfeatures`:  `n_urls`, `n_hashtags`, `n_mentions`, `n_chars`, `n_commas`, `n_digits`, `n_exclaims`, `n_extraspaces`, `n_lowers`, `n_lowersp`, `n_periods`, `n_words`, `n_caps`, `n_nonasciis`, `n_puncts`, `n_capsp`, `n_charsperword`,  `n_polite`, `n_first_person`, `n_first_personp`, `n_second_person`, `n_second_personp`, `n_third_person`, `n_tobe`, `n_prepositions`, and anything else that you can think of? 

We could exclude the sentiment scores and `word2vec` columns since those should be separate steps.

**Comment by EmilHvitfeldt** [comment]
Sure thing, that should be doable. I assume we are fine with the dependency? or should we reimplement?

**Comment by topepo** [comment]
I'dl like to use what's there (and give them credit) but very little is imported. Plus we would have to (re-)tokenize, which seems wasteful. 

@mkearney do you have any thoughts on this? It's a pain to document but could you export the worker functions (e.g. `second_personp()`, `tweet_features()`, etc)?

**Comment by EmilHvitfeldt** [comment]
> Plus we would have to (re-)tokenize, which seems wasteful.

For this case the `step_textfeatures` should ideally be applied directly to the text variable without any tokenization as tokenization removes evidence that textfeatures is trying to capture. Examples include 
- n_lowers = Number of lower case characters.
- n_extraspaces = Number of times more then 1 consecutive space have been used.
- n_periods = Number of periods.

Could the idea behind `step_textfeatures` be that a list of functions are run on the text variable to extract their information. This way we can have the default be something like this:

```r
default_functions <- list(n_lowers = textfeatures::n_lowers,
                          n_extraspaces = textfeatures::n_extraspaces,
                          ...,
                          n_periods = textfeatures::n_periods)

step_textfeatures(text, extract_functions = default_functions)
```

Then the user can modify the list to exclude or add other text features.

For this to work nicely it might be worth to let it run on a small test dataset to make sure the results come back numeric and the right sizes.

**Comment by mkearney** [comment]
I think this is a great idea and would definitely give [{textfeatures}](https://github.com/mkearney/textfeatures) a clearer [and better] purpose! I'll give the package a once-through but since you're already importing {dplyr} the only real additional baggage would probably be {text2vec}[http://text2vec.org/], right?

**Comment by EmilHvitfeldt** [comment]
We have text2vec too it wouldn't add anything.

**Comment by EmilHvitfeldt** [comment]
For documentation, I did some work in https://github.com/mkearney/textfeatures/pull/3. However if we are du export the individual functions I can help populate the documentation of those.
