### ISSUE TITLE
Question about stem steps

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/textrecipes#220]
What are the differences between `step_stem()` and `step_tokenize(token = "word_stems")`?

**Comment by EmilHvitfeldt** [comment]
`step_stem()` applies a stemming function to all the tokens, defaulting to `SnowballC::wordStem()` but other stemmer can be passed in using the `custom_stemmer` argument.

`step_tokenize(token = "word_stems")` means that tokenization will be done using the `tokenizers::tokenize_word_stems()` function, which uses its normal tokenizer and uses `SnowballC::wordStem()` internally.

For a {textrecipes} user, there should be no difference in output between `step_tokenize(token = "word_stems")` and `step_tokenize() |> step_stem()`. But `step_stem()` is useful if you want to use non-default stemmers or tokenizers
