### ISSUE TITLE
textrecipes removed from CRAN?

### ISSUE THREAD

**Issue by masurp** [tidymodels/textrecipes#253]
Hey everyone,

first, thanks for the great extension package for tidymodels. We are actually using both textrecipes and tidymodels in our master programme. 

Unfortunately, it seems that the package was taken down from CRAN yesterday!? Any known issues? Given that we are in the middle of the semester, would be great to know whether you are planning an update soon?

Thanks in advance!

P.S. To clarify, we can of course install from github, but students apparently are having some trouble with that, so just checking whether we can count on a CRAN version soon or whether we should redesign some exercises. Thanks.

**Comment by EmilHvitfeldt** [comment]
Hello @masurp 👋 

We are planning to send in a new version today!

**Comment by EmilHvitfeldt** [comment]
The package is back on CRAN as of 7 hours ago. I'm so sorry for the trouble this caused you

**Comment by masurp** [comment]
> The package is back on CRAN as of 7 hours ago. I'm so sorry for the trouble this caused you

Dear Emil, 

thanks so much and please don't be sorry! Students were more concerned than I was! I assumed that you would be quick to provide an update. 

Greetings from the Netherlands!
