### ISSUE TITLE
Add step for weighted log odds

### ISSUE THREAD

**Issue by scottfrechette** [tidymodels/textrecipes#38]
How hard would be to add a step for weighted log odds, similar to the new tidylo package?

**Comment by EmilHvitfeldt** [comment]
Hello @ scottfrechette! Thanks for your interest in `textrecipes`.

I'm going hold off for now with this. While feasible, I can't find a way to implement it in a way that is true to `recipes`. Right now calculations are done on a column by column basis, or on a collection of column all together.

Doing some weighted log odds would require one to specify a column of tokens (or columns of token counts) in addition to selection a column to weight against. 

I'm going to keep this issue open in case I find a good way of implementing this.

**Comment by scottfrechette** [comment]
That makes sense, I wondered if it was even possible. I've just had good luck using weighted log-odds in some modeling so thought I'd ask.

I appreciate you keeping it open just in case. I'd love to help any way I can.

**Comment by EmilHvitfeldt** [comment]
I'm going to close down this issue. I don't see a way to satisfactorily implement it.
