### ISSUE TITLE
textclean functions

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/textrecipes#49]
The textclean package has a number of functions that are useful for, well, cleaning text. Right now I'm using them via step_stem with `custom_stemmer = textclean::replace_ordinal` (etc).

What do you think about adding them as textrecipes steps (or maybe step_clean with an argument to specify which cleaners to use)? I can put together a PR if you're ok adding the dependency. If not, do you think a separate textcleanrecipes package makes sense?

**Comment by EmilHvitfeldt** [comment]
Hello @jonthegeek,

I like the idea behind what `textclean` is doing. However it comes with a lot of functions which would be a lot of steps too. I would be hesistant to add that many steps that are doing such similar things.

For now I would recommend still using `custom_stemmer` (i might get around to having a separate step to apply any text modifying function), and if you are in need of multiple cleaning operations you can `purrr::compose` them together

``` r
library(textclean)
library(textrecipes)
#> Loading required package: recipes
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

super_cleaner <- purrr::compose(
  replace_hash,
  replace_curly_quote, 
  replace_email, 
  replace_emoji
)

rec <- recipe(~ essay0, data = okc_text) %>%
  step_tokenize(all_predictors()) %>%
  step_stem(all_predictors(), custom_stemmer = super_cleaner) %>%
  step_tokenfilter(all_predictors())  %>%
  step_tfidf(all_predictors()) %>%
  prep()
```

<sup>Created on 2019-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jonthegeek** [comment]
Yeah, that's why I was thinking a single `step_clean` might be the way to go, with some sort of options of which cleaner(s) to use. I *can* do it without it being built in, it just cuts down the readability of my recipe a little (since I'm "hijacking" step_stem to do something that isn't really stemming).

In any case, I somehow didn't know about purrr::compose, so thanks for that! That will allow me to make some simple wrapper functions a bit cleaner.

**Comment by EmilHvitfeldt** [comment]
I'll an issue to create a step_clean in some capacity in a future update.  That way you don't have to hijack step_stem
