### ISSUE TITLE
cleanNLP steps? 

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/textrecipes#51]
I'm writing steps for annotation + doing things with the annotation using Stanford's coreNLP via the cleanNLP package. Would you want those in textrecipes, or should I keep them separate? It'll be a little bit before I have them clean enough to share (they're intermingled with some company-specific code right now to get things up and working for my project), but it shouldn't be too bad to pull them out in a bit. It'd add a fair amount of dependency overhead to textrecipes, though. Let me know what you think!

**Comment by EmilHvitfeldt** [comment]
I would like to see what you are doing with the annotations before commenting on the use inside textrecipes.

When you have time you can add an example of what you are doing. No rush!

**Comment by EmilHvitfeldt** [comment]
I have made recent changes to `step_tokenize()` to have a engine argument. So far we only have tokenizers and spacyr, but my plan is to add more support later.

My plan is to add support to the engines directly instead of going through cleanNLP.
