### ISSUE TITLE
Pre-tokenization steps

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/textrecipes#54]
The step_tokenize help says "Working will 'textrecipes' will always start by calling 'step_tokenize' followed by modifying and filtering steps." There are some things that are helpful to implement *before* tokenization, to avoid losing meaning. Examples in my current demo:

* spelling (I ended up just doing this in the original google sheet for the moment to make my life easier, but it could be implemented with hunspell)
* textclean::replace_contraction
* textclean::replace_time
* textclean::replace_number

For the demo, I rolled them up into a custom tokenizer, but it seems like they could fit here to provide users with some tasks that are likely to be common during text modeling.

Any thoughts?

Sorry for all the issue, hopefully I can help close some once I'm done sorting through this demo!

**Comment by EmilHvitfeldt** [comment]
Yes i like the idea of a string-in string-out step for pre-tokenization. 

The documentation should also reflect that we don't always start with `step_tokenize()` anymore.

**Comment by jonthegeek** [comment]
Yeah, that didn't feel right, but it's mostly true for the simple example I'm putting together (other than what's noted here), so I didn't dig into it too much.

**Comment by EmilHvitfeldt** [comment]
My recommendation for this issue is to simply use `step_mutate()` to do pre tokenization steps. We don't need to add another step to do the same thing :)
