### ISSUE TITLE
steps to get preserve argument

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/textrecipes#85]
Reference: https://github.com/tidymodels/recipes/issues/447

- [] `step_tokenize()`
- [] `step_textfeature()`
- [] `step_sequence_onehot()`
- [] `step_lda()`

**Comment by juliasilge** [comment]
FYI we have settled on using `keep_original_cols` as in tidymodels/recipes#635

That PR also has an exported function `get_keep_original_cols()` that may be useful

**Comment by EmilHvitfeldt** [comment]
How do I handle column names, right now `step_tokenize()` doesn't change the names of the resulting columns, which would then crash with the original that is hold back

**Comment by EmilHvitfeldt** [comment]
closing in favor of https://github.com/tidymodels/textrecipes/issues/139
