### ISSUE TITLE
step_word2vec -> step_word_embeddings?

### ISSUE THREAD

**Issue by kanishkamisra** [tidymodels/textrecipes#9]
I was wondering how the step_word2vec would work, in particular:

1. Will it just use the estimates for the word vectors from a pre trained word embedding model or something else?
2. If it is using estimates from a pretrained model, it would need a tokenized list-column so the workflow would be:
```
rec_object <- recipe(~., data = text_data) %>%
  step_tokenize(text_column) %>%
  step_word2vec(text_column, dims = 100)
```
  Is this correct?

3. If the package is going to use different methods (Mikolov's word2vec, GloVe, fasttext) for this, isnt it better if we just call it step_word_embed/step_embeddings (this can also go to the `embed` package now that I think about it, but it might be fine if it is kept in this since it is specific to nlp methods).

**Comment by EmilHvitfeldt** [comment]
I'm moving this conversation into #20 so I'm closing this issue :)
