### ISSUE TITLE
dials parameters

### ISSUE THREAD

**Issue by topepo** [tidymodels/textrecipes#96]
I'm working on another `dials` release. I was thinking of moving an `dials` parameter objects in ancillary packages into `dials`. Not required or anything, but having them in one place is nice from an organization standpoint. 

Let me know if you want to move any of yours in there (for `themis` too) and I can add them (or you can PR).

**Comment by EmilHvitfeldt** [comment]
It sounds like a good idea. I don't see any more `dials` parameter objects left in `textrecipes` so that package is good. I have left in `themis` I can move over later today https://github.com/tidymodels/themis/blob/7e704d4ae55a6d1a63edc9d61da97837289b3fa3/R/dials.R
